global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/alert_rules.yml

scrape_configs:
  # API Flask (métriques Prometheus sur /metrics)
  - job_name: "medassist-api"
    metrics_path: /metrics
    static_configs:
      - targets: ["api:5000"]

  # cAdvisor (conteneurs)
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  # Node Exporter (hôte)
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  # pushgateway 
  - job_name: "pushgateway"
    honor_labels: true
    static_configs:
      - targets: ["pushgateway:9091"]
